dist: xenial
language: python

stage: test

python:
  - 3.6
  - 3.7

branches:
  only:
  - master
  - devel

before_install:
  - pip install poetry

install:
  - poetry install -v

script:
  - pytest

notifications:
  slack:
    secure: Hz3J3AluB4lN+YxRxsV93IjL0j5pevTDXflw9YN6VWH99BL7OEJxhsOGtqHLqbUDa4+XPVGgFsAXiHZPO19d4jng5uIRbj7VZNFK7gwn58S3GfyMeGOjdYh0fB/xbgYn2jYM1cWGpanwtXq5aDVEHPL2M803UMyyAM2F/HmysRdr50VFYQJQ4It77H+vajtyZGL7ztuAuY2AD10v5PctGk9JYt/EQWbYwdtCSdUNHublwiLRzvyvT/LT//MzsELuMdKzaVPQn01PMjZNerOsBszgscfBEOCSJtLaCjlQwvONWFCx9xP0kVBfMQo55XQaD9cSyswVnigzTihGaozU+149ZTWpB57Xd0tAsQ05GJIatbB+8FGKmFkFjvkxBSGXkL3AYN0engOpZyR4/KHrmKlSu2oCLbJMqvdnjlm/V41IV8UiMCgRCF/kMvHcHtgnBezV36+0eRMEWW7Vz7GAh7Eeqo3kcSTFG6OHD5kkiVoDW+S64cunHcb6k8sM+N/WxadpFV+jzzK/ovoDOA7G7gxhzgONJ8BYC2azZmRf+JfhosbRTh7PgMEi1srOlmJSZAzbE4IVJYcqOWbIdHO+v+1scYepPvzOuCXlD98UNhOOtAaMKXy9zGz2IYgbcswHOdUFnD2ei53pGz5QLJ0VLh7ZpBYfEEVB7uKbKsGuWB8=

jobs:
  include:
    - stage: deploy
      python: 3.7
      install: 
        - pip install poetry
        - poetry install -v
      script:
        - mkdocs build
      deploy: &gh-pages
        provider: pages
        local_dir: site
        skip_cleanup: true
        keep_history: true
        fqdn: nanocompore.rna.rocks
        on:
          branch: master
        github_token:
          secure: "v/yqJd0NF/4vgOWFOYuaxD8bUd9XESLc/K1H0Uer/Fwc/gQqzSJZ2CsqYeoI1dxOM9dNcQDVGi4bLTx0mXLI5fwmNbI3aLbBEBD5s3KCZ3PT0woFwnorPnpNHsDPm9aDAwg4Rc7S9ljdLByKBBJTItNBi0qD8nVaiVi0pGwM2pokjefkuM/tr0yUFMBxkjGOrNnboSd9JSSF+42uBN1ajb229jCiqMJWw0Q1K+B/+4KHBKaUgM0Bwt36kuCwQaZdoybxmMkdAK5hWaM8WBTQ7QIGqgHwkXQ1RkXK4dd1wE3SxfX4UNJb9SuiTslQn3rZGOJ9EA9XEGvePhI+G8w8HmxH3ps+y4QQLGf39mFLGJZgmHMzNoBfbpL8AKhk8g+T+bF4eVaJArXLy58dLKs97gBc6XJjxnqMn/we4roTHYHa1jSlTRlXXunmM8BNLXb8zck2nGUbBrtGPUvL7ZUs3LrlPN9AKLas4swWTJoPxFym0OG/0JXMu8nc/t7bc4jn7usZxThXvsjILUCocvjnvJ98NAxrCHDjFFJ0VJzNvhSx0PY2/VtIYe9wf6/Geb0NXrDHPImj/qlGewHN9s30YmOXf8TiEOKgBR3u3M1gy2jYtzXxlD5N6xWDFFteSZbc2uCiaiPvf9F+6Bo4q0jr5gcuEik9QJ6YffkrQ5NOO18="
