import pytest
from nanocompore.TxComp import *
from scipy.stats import combine_pvalues
import numpy as np
from unittest import mock
from nanocompore.SimReads import SimReads, parse_mod_pos_file
from nanocompore.SampComp import SampComp


@pytest.fixture(scope="module")
def fasta_file(tmpdir_factory):
    fasta_file = tmpdir_factory.mktemp("fasta").join("reference.fa")
    with open(fasta_file, 'w') as f:
        f.write('>Ref_001\nAATGGGAACGCTTAAACTTACCAAAGTGGTAGGGCATTATAACCCGATGAGACGTGTTACCCCTCAAAGGGCGGTACACCAACTTCAGACTGAGGTTCGATCTCGTGAAATGTCAGCAAGACCTCCACTCCGAAGCCATGAAGCGTTGCCGGGGATTAGCAAGCATCATGTTTACGAATTATATATGCAGACCGTCTTAACCTGGTCCCTAACTAATAATTTATAGTTCTTAGGACGCTCTTGATGATACCCGACGCCCGGCGATCTTATCATCTTTGGCCCCTTCTTCCGGATAGTGTAACGATCATAATTTTCTGCGGAACCTGAAGTTTGCTTTGAGCAAAACTGAGGAGGTTAGTTCTAATATCTGTGTCGCCAAAAACAGCACGATTCTCGACCCGGCGCCGCCACTCGCGACAGCCTTGGGTCCCAGATGCGAACTAATACTAACGGCCCCGACTGCAGAGAAATTTCGGCACACACTCATCTTTTTGCAGCCG\n')
        f.write('>Ref_002\nAATGAGGGATCGAAGCGA\n')
    return(str(fasta_file))

@pytest.fixture(scope="module")
def nanopolishcomp_test_files(tmpdir_factory, fasta_file):
    """ Generate simulated data with SimReads() """
    tmp_path=tmpdir_factory.mktemp("generated_data")
    data_rand_seed=869
    fn_dict={'S1':{}, 'S2':{}}
    for rep in [1,2,3,4]:
        SimReads (
            fasta_fn=fasta_file,
            outpath=str(tmp_path),
            outprefix="control_rep"+str(rep),
            run_type = "RNA",
            intensity_mod_loc=0,
            intensity_mod_scale=0,
            dwell_mod_loc=0,
            dwell_mod_scale=0,
            mod_reads_freq=0,
            mod_bases_freq=0,
            mod_bases_type="A",
            mod_extend_context=False,
            pos_rand_seed=66,
            data_rand_seed=data_rand_seed+rep,
            not_bound=True,
            log_level="debug",
            overwrite=True)
    
        SimReads (
            fasta_fn=fasta_file,
            outpath=str(tmp_path),
            outprefix="mod_rep"+str(rep),
            run_type = "RNA",
            intensity_mod_loc=10,
            dwell_mod_loc=0.05,
            mod_reads_freq=0.5,
            mod_bases_freq=0.25,
            mod_bases_type="A",
            mod_extend_context=False,
            pos_rand_seed=66,
            data_rand_seed=data_rand_seed+rep,
            not_bound=True,
            log_level="debug",
            overwrite=True)
        fn_dict['S1']['R'+str(rep)]="{}/control_rep{}.tsv".format(str(tmp_path), rep)
        fn_dict['S2']['R'+str(rep)]="{}/mod_rep{}.tsv".format(str(tmp_path), rep)

    return((fasta_file, fn_dict, str(tmp_path)))

@pytest.mark.parametrize("method", ["GMM", "KS", "TT", "MW"])
@pytest.mark.parametrize("context", [2,3])
@pytest.mark.parametrize("context_weight", ["uniform", "harmonic"])
def test_1(nanopolishcomp_test_files, method, context, context_weight):
    fasta_file, fn_dict, tmp_path = nanopolishcomp_test_files
    s = SampComp(eventalign_fn_dict=fn_dict,
            outpath=tmp_path,
            outprefix="nanocompore",
            fasta_fn=fasta_file,
            comparison_methods = method,
            logit = True,
            allow_warnings = False,
            sequence_context = context,
            sequence_context_weights = context_weight,
            downsample_high_coverage = None,
            overwrite=True)
    db = s()
    db.save_report("{}/report_{}_{}_{}.txt".format(tmp_path, method, context, context_weight))
    # check that the small reference is discarded by min_ref_length
    assert len(db.ref_id_list) == 1
    # Load the expected modified positions from the files generated by SimReads()
    expected_pos = parse_mod_pos_file(tmp_path+"/mod_rep1_pos.tsv")

    # Assert that the modified positions identified by SampComp match the expected ones
    for ref in db.ref_id_list:
        for test in [t for t in db._metadata["pvalue_tests"] if "context" not in t]:
            sig=list(db.results[(db.results['ref_id']==ref) & (db.results[test]<0.05)]['pos']) 
            assert expected_pos[ref] == sig

def test_2(nanopolishcomp_test_files):
    fasta_file, fn_dict, tmp_path = nanopolishcomp_test_files
    s = SampComp(eventalign_fn_dict=fn_dict,
            outpath="tmp/",
            outprefix="nanocompore",
            fasta_fn=fasta_file,
            allow_warnings=False,
            min_ref_length = 5,
            downsample_high_coverage = None,
            overwrite=True)
    db = s()
    db.save_report("tmp/report.txt")
    # check that the small reference is not discarded by min_ref_length
    assert len(db.ref_id_list) == 2

def test_2(nanopolishcomp_test_files):
    fasta_file, fn_dict, tmp_path = nanopolishcomp_test_files
    s = SampComp(eventalign_fn_dict=fn_dict,
            outpath="tmp/",
            outprefix="nanocompore",
            fasta_fn=fasta_file,
            allow_warnings=False,
            min_ref_length = 5,
            downsample_high_coverage = None,
            overwrite=True)
    db = s()
    db.save_report("tmp/report.txt")
    # check that the small reference is not discarded by min_ref_length
    assert len(db.ref_id_list) == 2

